site_name: scoper
site_url: https://scoper.readthedocs.io
site_favicon: img/favicon.ico
repo_url: https://bitbucket.org/kleinstein/scoper
edit_uri: src/master/docs/
theme:
  name: readthedocs
  navigation_depth: 2
  collapse_navigation: False
  sticky_navigation: False
  locale: en
  logo: null  
  titles_only: False
markdown_extensions:
  - def_list
  - sane_lists
  - smarty
  - toc:
      baselevel: 1
      toc_depth: 1-4
      permalink: True
docs_dir: 'docs'
nav:
  - 'Immcantation Portal': https://immcantation.readthedocs.io/
  - 'About':
    - 'Introduction': index.md
    - 'Download & Installation': install.md
    - 'Package Overview': topics/scoper.md
    - 'Release Notes': news.md
    - 'Related Projects': projects.md
  - 'Vignettes':
    - 'Clonal Partitioning': vignettes/Scoper-Vignette.md
  - 'Help Topics':
    - topics/identicalClones.md
    - topics/hierarchicalClones.md
    - topics/spectralClones.md
    - topics/plotCloneSummary.md
    - topics/ScoperClones-class.md
    - topics/ExampleDb.md
